/**
 * The starting rows for a database that has none.
 *
 *   npm run db:seed
 *
 * Data, not schema — which is why it is here and not in a migration. A migration
 * describes the shape every copy of this database must have; these are six
 * sports cards and three circuits that a NEW install starts with and that
 * production has had for months. Putting them in 0001 would mean re-inserting
 * them into every branch cut from production, and deleting one would mean it
 * came back on the next deploy.
 *
 * Each half only fires on an empty table, so this cannot resurrect a card
 * somebody deleted on purpose, and running it twice does nothing the second
 * time.
 *
 * It was `seedSports` and `seedTracks` in scripts/schema.mjs, which ran on every
 * `npm run migrate`. The four backfills that sat beside them are gone: two are
 * now statements in 0001, and the two that filled blanks from these lists —
 * `backfillSportPhotos` and `backfillTrackDetails` — existed only for rows
 * seeded before their columns did, and are verified applied against production.
 * The seeds below write every column, so a fresh install never needs them.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { neon } from "@neondatabase/serverless";

/**
 * Generated by scripts/export-seed-content.ts from the DEFAULT_* documents that
 * used to live in src/lib, in the row shape `writePage` writes. Edit the JSON —
 * there is nothing left to keep it in step with.
 */
const PAGE_CONTENT = ["landing", "incrc"].map((key) =>
  JSON.parse(readFileSync(join("scripts", "seed-data", `${key}.json`), "utf8"))
);

/** Kept in step with SEED_SPORTS in src/lib/sports.ts. */
const SEED_SPORTS = [
  {
    title: "CTR-JK Tyre FMSCI Indian National Car Racing Championship",
    text: "National Circuit Program",
    details:
      "A professional national ladder connecting karting graduates to full circuit competition under one unified banner.",
    logo_url: "/images/sports/national-racing.webp",
    photo_url: "https://cdn-s3.autocarindia.com/legacy/cdni/ExtraImages/20230724125143_Arjun_Balu_Indian_Touring_Cars.jpg?w=728&q=75&fm=auto",
    href: "/incrc",
    sort_order: 10,
  },
  {
    title: "Formula 4 Racing",
    text: "CTR Racing Development",
    details:
      "From telemetry to racecraft, the F4 pathway develops next-generation circuit talent with measurable rigor.",
    logo_url: "/images/sports/formula-4.webp",
    photo_url: "https://raw.githubusercontent.com/Krishna-Vijay-G/asset-temp/refs/heads/main/114A3449%20(Medium).JPG",
    href: "https://chennaiturboriders.in",
    sort_order: 20,
  },
  {
    title: "Field Hockey",
    text: "Accord Tamil Nadu Dragons",
    details:
      "Pace-driven pressing and disciplined circle execution make our hockey program sharp and competitive.",
    logo_url: "/images/sports/hockey.webp",
    photo_url: "https://tamilnadudragons.in/assets/images/Banner2.jpg",
    href: "https://tamilnadudragons.in",
    sort_order: 30,
  },
  {
    title: "Pickleball",
    text: "Chennai Super Warriors",
    details:
      "Explosive hand-speed, compact court strategy, and doubles chemistry define CTR's pickleball identity.",
    logo_url: "/images/sports/pickleball.webp",
    photo_url: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=72",
    href: "",
    sort_order: 40,
  },
  {
    title: "Volleyball",
    text: "Kasi Warriors",
    details:
      "Vertical athleticism and controlled transition play power our volleyball program across elite competitions.",
    logo_url: "/images/sports/volleyball.webp",
    photo_url: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=800&q=72",
    href: "",
    sort_order: 50,
  },
  {
    title: "Cricket",
    text: "Accord Warriors",
    details:
      "Structured batting depth, precision bowling plans, and relentless fielding standards anchor this unit.",
    logo_url: "/images/sports/cricket.webp",
    photo_url: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=72",
    href: "",
    sort_order: 60,
  },
];

/** Kept in step with SEED_TRACKS in src/lib/tracks.ts. */
const SEED_TRACKS = [
  {
    name: "Kari Motor Speedway",
    slug: "kari-motor-speedway",
    location: "Chettipalayam, Coimbatore, Tamil Nadu",
    photo_url: "",
    map_url: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Kari_Motor_Speedway_Layout.jpg",
    length: "2.10 km",
    turns: "15",
    direction: "Clockwise",
    opened: "2003",
    broke_ground: "2002",
    former_names: "",
    owner: "B. Vijay Kumar (LG Sports)",
    fia_grade: "3",
    coordinates: "10°54′5″N 77°3′3″E",
    links: [{ label: "Official site", href: "https://lgsports.co.in" }],
    major_events: [
      "Indian Racing League",
      "F4 India",
      "JK Tyre National Racing Championship",
      "Formula LGB 1300 / LGB 4",
      "Indian National Motorcycle Racing Championship",
    ].join("\n"),
    lap_record_time: "1:03.296",
    lap_record_year: "2024",
    note: "A technical, tight circuit named in memory of legendary Indian racer and constructor S. Karivardhan.",
    sort_order: 10,
  },
  {
    name: "Bren Raceway",
    slug: "bren-raceway",
    location: "Doddaballapur, Bengaluru, Karnataka",
    photo_url: "",
    map_url: "",
    length: "4.10 km",
    turns: "14",
    direction: "Clockwise",
    opened: "2024",
    broke_ground: "2022",
    former_names: "",
    owner: "Boopesh Reddy (Bren Garage)",
    fia_grade: "2",
    coordinates: "13°22′38″N 77°30′55″E",
    links: [{ label: "Official site", href: "https://brengarage.com" }],
    major_events: [
      "Track Days",
      "Supercar Experience",
      "Private Testing",
      "Motorsport Training & Driver Development",
    ].join("\n"),
    lap_record_time: "",
    lap_record_year: "",
    note: "FIA Grade 2 specification private racetrack designed for testing, performance driving, and exclusive motorsport events.",
    sort_order: 20,
  },
  {
    name: "Madras International Circuit",
    slug: "madras-international-circuit",
    location: "Irungattukottai, Chennai",
    photo_url:
      "https://cdn-s3.autocarindia.com/legacy/cdni/ExtraImages/20240920010433_Madras_international_karting_arena.jpg",
    map_url:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Irungattukottai_Race_Track_map_--_Full_track.svg/960px-Irungattukottai_Race_Track_map_--_Full_track.svg.png",
    length: "3.71 km",
    turns: "12",
    direction: "Clockwise",
    opened: "1990",
    broke_ground: "1988",
    former_names: "Madras Motor Race Track; Irungattukottai Race Track",
    owner: "Madras Motor Sports Club",
    fia_grade: "2",
    coordinates: "13°0′9″N 79°59′9″E",
    links: [{ label: "Official site", href: "https://en.madrasmotorsports.com" }],
    major_events: [
      "MRF Formula 2000",
      "Indian Racing League",
      "F4 India",
      "F4 SEA",
      "Asia Road Racing Championship",
      "Asian F3",
    ].join("\n"),
    lap_record_time: "1:30.323",
    lap_record_year: "2020",
    note: "A long back straight into a hairpin — the season's decider.",
    sort_order: 30,
  },
];

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is not set. Make sure .env exists in the project root.");
  process.exit(1);
}

const sql = neon(process.env.DATABASE_URL);

/*
 * Schema-qualified, unlike the application. The app relies on the search_path
 * 0001 sets on the database, which is the right trade for a hundred queries; a
 * setup script that may be the first thing ever run against a database is better
 * off saying where it means.
 */
async function seedSports() {
  const [{ count }] = await sql`SELECT count(*)::int AS count FROM ctr.sports`;
  if (count > 0) return 0;

  for (const sport of SEED_SPORTS) {
    await sql`
      INSERT INTO ctr.sports (title, text, details, logo_url, photo_url, href, sort_order)
      VALUES (${sport.title}, ${sport.text}, ${sport.details}, ${sport.logo_url},
              ${sport.photo_url}, ${sport.href}, ${sport.sort_order})
    `;
  }

  return SEED_SPORTS.length;
}

async function seedTracks() {
  const [{ count }] = await sql`SELECT count(*)::int AS count FROM ctr.tracks`;
  if (count > 0) return 0;

  for (const track of SEED_TRACKS) {
    const [{ id }] = await sql`
      INSERT INTO ctr.tracks (
        name, slug, location, photo_url, map_url, length, turns, direction, opened,
        broke_ground, former_names, owner, fia_grade, coordinates, capacity,
        major_events, lap_record_time, lap_record_year, note, sort_order
      )
      VALUES (
        ${track.name}, ${track.slug}, ${track.location}, ${track.photo_url ?? ""}, ${track.map_url ?? ""},
        ${track.length ?? ""}, ${track.turns ?? ""}, ${track.direction ?? ""},
        ${track.opened ?? ""}, ${track.broke_ground ?? ""}, ${track.former_names ?? ""},
        ${track.owner ?? ""}, ${track.fia_grade ?? ""}, ${track.coordinates ?? ""},
        ${track.capacity ?? ""}, ${track.major_events ?? ""},
        ${track.lap_record_time ?? ""}, ${track.lap_record_year ?? ""},
        ${track.note ?? ""}, ${track.sort_order}
      )
      RETURNING id
    `;

    // Rows since 0004, and the column they used to live in was dropped by 0008.
    // `position` is 1-based to match what the admin writer produces.
    const links = (track.links ?? []).filter((link) => link.href);

    for (const [index, link] of links.entries()) {
      await sql`
        INSERT INTO ctr.track_links (track_id, position, label, href)
        VALUES (${id}, ${index + 1}, ${link.label ?? ""}, ${link.href})
      `;
    }
  }

  return SEED_TRACKS.length;
}

/**
 * The landing and INCRC pages, as rows.
 *
 * These two documents were `DEFAULT_LANDING_CONTENT` and `DEFAULT_INCRC_CONTENT`
 * in src/lib — TypeScript constants that rendered whenever the page had no row,
 * which was always, because nothing ever wrote one. They are the page now, so
 * they are seeded like everything else and the constants are gone.
 *
 * scripts/seed-data/*.json is generated, not typed: the shape it lands in is
 * exactly what `writePage` produces, so the admin re-saving a page overwrites it
 * with the same layout it read. See the header of the (now deleted) exporter.
 *
 * Per PAGE rather than per table — a database that has the landing page but not
 * INCRC gets INCRC, and one that has both is left alone. Anything else would
 * either resurrect a section somebody deleted or refuse to seed a half-empty
 * install.
 */
async function seedPageContent() {
  const seeded = [];

  for (const page of PAGE_CONTENT) {
    const key = page.page_key;

    const [{ count }] = await sql`
      SELECT count(*)::int AS count FROM ctr.page_sections WHERE page_key = ${key}
    `;
    if (count > 0) continue;

    for (const section of page.sections) {
      await sql`
        INSERT INTO ctr.page_sections (page_key, section_id, position, visible, data)
        VALUES (${key}, ${section.section_id}, ${section.position}, ${section.visible},
                ${JSON.stringify(section.data)}::jsonb)
      `;
    }

    for (const banner of page.banners) {
      await sql`
        INSERT INTO ctr.banners (page_key, banner_id, position, template, image, fit,
                                 focus, overlay, title, subtitle, cta_label, cta_href)
        VALUES (${key}, ${banner.banner_id}, ${banner.position}, ${banner.template},
                ${banner.image}, ${banner.fit}, ${banner.focus}, ${banner.overlay},
                ${banner.title}, ${banner.subtitle}, ${banner.cta_label}, ${banner.cta_href})
      `;
    }

    for (const round of page.rounds) {
      await sql`
        INSERT INTO ctr.calendar_rounds (page_key, position, round, venue, city,
                                         date_from, date_to, dates, status, track_id)
        VALUES (${key}, ${round.position}, ${round.round}, ${round.venue}, ${round.city},
                ${round.date_from}, ${round.date_to}, ${round.dates}, ${round.status},
                -- Resolved the way writePage resolves it: a circuit that is not
                -- there lands as NULL, and the card falls back to the venue and
                -- city beside it.
                (SELECT id FROM ctr.tracks WHERE id::text = ${round.track_id}))
      `;
    }

    for (const post of page.posts) {
      await sql`
        INSERT INTO ctr.posts (page_key, post_id, position, image, category, date,
                               title, excerpt, href)
        VALUES (${key}, ${post.post_id}, ${post.position}, ${post.image}, ${post.category},
                ${post.date}, ${post.title}, ${post.excerpt}, ${post.href})
      `;
    }

    for (const partner of page.partners) {
      await sql`
        INSERT INTO ctr.partners (page_key, position, name, logo, href)
        VALUES (${key}, ${partner.position}, ${partner.name}, ${partner.logo}, ${partner.href})
      `;
    }

    seeded.push(
      `${key} (${page.sections.length} section(s), ${page.banners.length} banner(s)` +
        (page.rounds.length ? `, ${page.rounds.length} round(s)` : "") +
        (page.posts.length ? `, ${page.posts.length} post(s)` : "") +
        (page.partners.length ? `, ${page.partners.length} partner(s)` : "") +
        ")"
    );
  }

  return seeded;
}

try {
  const sports = await seedSports();
  console.log(sports ? `Seeded ${sports} sports.` : "ctr.sports already has rows — nothing seeded.");

  const tracks = await seedTracks();
  console.log(tracks ? `Seeded ${tracks} circuits.` : "ctr.tracks already has rows — nothing seeded.");

  // After the circuits, so a calendar round can resolve the track it names.
  const pages = await seedPageContent();
  if (pages.length === 0) {
    console.log("ctr.page_sections already has both pages — nothing seeded.");
  } else {
    for (const line of pages) console.log(`Seeded ${line}.`);
  }
} catch (error) {
  /*
   * 42P01 is undefined_table and nothing else. This used to match "does not
   * exist" anywhere in the message, which also catches undefined_column (42703)
   * — so a seed that had fallen behind a migration reported a missing schema and
   * sent you to re-run a migrate that had already worked.
   */
  if (error.code === "42P01") {
    console.error("The schema is not there yet. Run npm run db:migrate first.");
    process.exit(1);
  }

  console.error("Failed:", error.message);
  process.exit(1);
}
